cmake_minimum_required(VERSION 3.6)

SET(CMAKE_ASM_FLAGS "")
SET(CMAKE_ASM_FLAGS_DEBUG "${CMAKE_ASM_FLAGS_DEBUG} -DDEBUG")
SET(CMAKE_ASM_FLAGS_RELEASE "${CMAKE_ASM_FLAGS_RELEASE} -DNDEBUG")
SET(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -D__STARTUP_CLEAR_BSS -g -mcpu=cortex-m0plus -Wall -mfloat-abi=soft")
SET(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS}  -mthumb -fno-common -ffunction-sections -fdata-sections")
SET(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -ffreestanding -fno-builtin -mapcs -std=c11")
SET(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -D__NO_SYSTEM_INIT=1 -x assembler-with-cpp")

SET(CMAKE_C_FLAGS "")
SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -DDEBUG -g -O0")
SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -DNDEBUG -Os")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCPU_MKL25Z128VLK4=1 -DFRDM_KL25Z -DFREEDOM")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mcpu=cortex-m0plus -Wall -Werror -mfloat-abi=soft")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mthumb -MMD -MP -fno-strict-aliasing -fshort-enums --specs=nosys.specs")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mapcs -std=c11") # -mabi=aapcs")

SET(CMAKE_EXE_LINKER_FLAGS "")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--gc-sections")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--static")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--cref")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -mcpu=cortex-m0plus -Wall -mfloat-abi=soft") 
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fno-builtin -mthumb -mapcs") 
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fno-common -ffunction-sections -fdata-sections -ffreestanding")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Xlinker -z -Xlinker muldefs")

SET(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -g")

